name: deploy to GCE
on:
  push:
    braches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - run: |
          gcloud compute ssh ${{ secrets.GCP_SA_NAME }}@gce-test --zone=${{ secrets.GCP_PROJECT_ZONE }} --command="hogehoge"